[package]
name = "bitbar-twitch"
version = "0.2.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
itertools = "0.8"
notify-rust = "3"
reqwest = "0.9" #TODO upgrade to 0.10 and rework to use async
serde_json = "1"
xdg-basedir = "1"

[dependencies.bitbar]
version = "0.3"
features = ["base64"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.timespec]
git = "https://github.com/fenhl/rust-timespec"
