[package]
name = "bitbar-twitch"
version = "0.2.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
derive_more = "0.99"
itertools = "0.8"
pin-utils = "0.1"
serde_json = "1"
xdg-basedir = "1"

[dependencies.bitbar]
version = "0.4"
features = ["base64", "url1"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.futures]
version = "0.3"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.timespec]
git = "https://github.com/fenhl/rust-timespec"

[dependencies.tokio]
version = "0.2"
features = ["macros", "rt-threaded"]

[dependencies.twitch_helix]
git = "https://github.com/fenhl/rust-twitch-helix"
